title: 分からんラジオ
url: https://wakaran.yhmk.org

description: 世紀の大発見も夢のようなアイデアも小さな問いかけから生まれた。分からんラジオは、同棲している男女二人が日々の生活の中で感じた小さな疑問へ果敢に立ち向かっていくポッドキャストです。
author: YHMK

author_url: "https://yhmk.org/"
download_url: "/api/download?filename="

email: wakaran@yhmk.org
itunes_categories:
  - Comedy
  - Arts
  - Science
  - Education
episodes_per_feed_page: 100

date_format: ordinal

language: ja
explicit: "no"

license: CC BY 4.0
license_url: https://creativecommons.org/licenses/by/4.0/
license_image_url: https://i.creativecommons.org/l/by/4.0/88x31.png

spotify_url: https://open.spotify.com/show/3QleUJ3vpFiEafMjBMv4Zq
apple_url: https://podcasts.apple.com/us/podcast/分からんラジオ/id1617493816
google_url: https://podcasts.google.com/feed/aHR0cHM6Ly93YWthcmFuLnlobWsub3JnL2VwaXNvZGVzLm1wMy5yc3M

episode_feed_formats: 
  - mp3
